### ISSUE TITLE
繰返し可能な型からシーケンス型へ変更する

### ISSUE THREAD

**Issue by HayaoSuzuki** [pyconjp/pycamp.pycon.jp#106]
## 目的

- 「2.1.2. 文字列」コラムの記述が正確ではないので修正したい。
    - 「繰返し可能な型(シーケンス)は順序を持つ型で、Python標準では3つの型があります。」
    - シーケンス型には`__getitem__`でアクセス可能という特徴もある。
    - 標準のシーケンス型は`list`, `str`, `tuple`, `range`, `bytes`など3つ以上ある。

## 内容

- [ ] 「シーケンス型は順序を持つ型で、Python標準にはリスト(list)型、タプル(tuple)型、レンジ(range)型などがあります。」と修正する。
- [ ] 後の章に備えてインデックスにも触れておく。

**Comment by takanory** [comment]
merged
