### ISSUE TITLE
インデックスアクセスとスライスを明確に区別する

### ISSUE THREAD

**Issue by HayaoSuzuki** [pyconjp/pycamp.pycon.jp#107]
## 目的

- 4.2. リスト（list）の「リスト 4.2」のインデックスによるアクセスとスライスを混同している個所を修正したい。
    - `>>> ['spam', 'ham', 'egg'][0]              # リストのスライス(0番目)`
    - `['spam', 'ham', 'egg'][0]`は`'spam'`であるが、`['spam', 'ham', 'egg'][0:1]`は`['spam']`となる。

- 4.3. タプル（tuple）の「リスト 4.9」のインデックスによるアクセスとスライスを混同している個所を修正したい。
    - `>>> ('spam', 'ham', 'egg')[0]              # タプルのスライス(0番目)`
    - 上記と同様

## 内容

- [ ] `>>> ['spam', 'ham', 'egg'][0]              # リストの0番目を取得する`に変更する
- [ ] `>>> ('spam', 'ham', 'egg')[0]              # タプルの0番目に変更する`に変更する

**Comment by takanory** [comment]
mergeしました
