### ISSUE TITLE
集合の「長さ」ではなく「要素の個数」とする

### ISSUE THREAD

**Issue by HayaoSuzuki** [pyconjp/pycamp.pycon.jp#109]
## 目的

- 「4.5. 集合」の`len()` 関数の記述においてリストやタプルと同様に「長さ」と表記しているが、集合の場合は「要素の個数」や「要素数」の方が適切である。

## 内容

- [ ] 集合型の要素数に「長さ」と記述してある箇所を「要素の個数」や「要素数」などに置き換える

**Comment by takanory** [comment]
mergeしました
