### ISSUE TITLE
 テキストにAnanonda,Python2.7が駄目であるということを明記する

### ISSUE THREAD

**Issue by koedoyoshida** [pyconjp/pycamp.pycon.jp#119]
## 目的

- テキストにAnanonda,Python2.7が駄目であるということを明記する

## 内容

20171219 Python Boot Camp 忘年会議議事録より
事前準備(Pythonインストール)が足りていない/勘違いしているため、ついてこれない人が数名ずつ散見される(吉田)
事前に連絡はしているけど、それ以上は無理かな(たかのり)
anacondaはいるよねー(たかのり)

この手順でインストールしてと書いている(たかのり)
すでにある人は「いいか」と思うので、ダメだよって書くべき(吉田)
なるほど(たかのり)
別のスクールでanacondaを入れていた人がいたので、両立する方法を提案してもよいかも(片柳)

**Comment by sakurai-youhei** [comment]
Ananondaではない前提であれば、それと整合性を取るためにCondaの記述はなくしたほうが良い気がしました。

https://github.com/pyconjp/pycamp.pycon.jp/blob/master/source/textbook/6_venv.rst#conda-%E3%81%AE%E5%A0%B4%E5%90%88

**Comment by terapyon** [comment]
すでに、 #120 で修正されている。
