### ISSUE TITLE
Windows環境でのvenvについていくつか修正提案

### ISSUE THREAD

**Issue by takanory** [pyconjp/pycamp.pycon.jp#126]
## 目的

- Windows環境でテキスト通りに実施すると少しハマりやすいとのフィードバックをもらった(thx: かまたま だいさん)

## 内容

```
1.2. ターミナルの準備
　Windowsは、cmd.exe(コマンドプロンプト)でなく、PowerShellをターミナルとして利用することを
　もう少し協調しておかないと、今回ハマっている人がいましたが、毎回ハマる人が出そうです。


5.1.2. ファイルへの書き込み
　書き込んだファイルの内容を powershell 上で確認しようとされてましたが、
　ファイルの内容をutf8 で表示するコマンドは以下の通りです。

　Get-Content -Encordinf utf8 <ファイルのパス>

　Get-Contentのエイリアスとしてtypeが使用できるため、下記でもいけます。

　type -Encordinf utf8 <ファイルのパス>


7.2. 環境構築
　リスト 7.1 スクレイピング用のvenv環境を構築 において
　Windowsの場合のactivate方法がコメントで記載されていませんでした。

　以下のように追記された方がいいと思います。
　$ source env/bin/activate  # Windowsの場合は env\Scripts\Activate.ps1
```

**Comment by soogie** [comment]
修正提案を受けて具体的な修正案

> 1.2. ターミナルの準備
> 　Windowsは、cmd.exe(コマンドプロンプト)でなく、PowerShellをターミナルとして利用することを
> 　もう少し協調しておかないと、今回ハマっている人がいましたが、毎回ハマる人が出そうです。
> 
「powershellと入力します」という説明の後ろに「（コマンドプロンプトは使いません）」と追記

> 5.1.2. ファイルへの書き込み
> 　書き込んだファイルの内容を powershell 上で確認しようとされてましたが、
> 　ファイルの内容をutf8 で表示するコマンドは以下の通りです。
> 
> 　Get-Content -Encordinf utf8 <ファイルのパス>
> 
> 　Get-Contentのエイリアスとしてtypeが使用できるため、下記でもいけます。
> 
> 　type -Encordinf utf8 <ファイルのパス>
> 
テキストには表記がないので修正なし。講師は知っておくと便利ですね。

> 7.2. 環境構築
> 　リスト 7.1 スクレイピング用のvenv環境を構築 において
> 　Windowsの場合のactivate方法がコメントで記載されていませんでした。
> 
> 　以下のように追記された方がいいと思います。
> 　$ source env/bin/activate  # Windowsの場合は env\Scripts\Activate.ps1

すでにWindowsの場合の起動方法が記載されているので修正不要
