### ISSUE TITLE
pycampテキスト更新: スクレイピングの対象サイトを変える

### ISSUE THREAD

**Issue by KobaTomo** [pyconjp/pycamp.pycon.jp#154]
## 目的

- スクレイピングのサンプルのサイトがpycon jp 2017と古いので変えたい (ISSHA-2566)
- https://pyconjp.atlassian.net/browse/ISSHA-2566

## 内容

- [ ] www.pycon.jp のなにか? https://www.pycon.jp/
- [ ] pyconjp blog のなにか? https://pyconjp.blogspot.com/
- [ ] python.orgのなにか? https://python.org/
- [ ] docs.python.org のなにか?
https://docs.python.org/ja/
https://docs.python.org/ja/3/library/index.html
https://docs.python.org/ja/3/library/functions.html
組み込み関数の数は何個か
数が変わっている。なにが増えたのかとか
- [ ] https://peps.python.org/

**Comment by kuma127** [comment]
2022のもので一新できないか試してみます

**Comment by kuma127** [comment]
PyConJPのスポンサー一覧は2018からvue+nuxtの形式になって取得が難しくなったんですね…
↑から色々探してみます
