### ISSUE TITLE
「1.4. 注意事項」にJupyter、Google Colaboratoryでは実習できない旨を追記

### ISSUE THREAD

**Issue by ryu22e** [pyconjp/pycamp.pycon.jp#156]
## 目的

- この issue の目的
  - 「1.4. 注意事項」にJupyter、Google Colaboratoryでは実習できない旨を追記

## 内容

- [x] 「1.4. 注意事項」( https://pycamp.pycon.jp/textbook/1_install.html#id5 )の「Python 2.7等のPython2系やAnacondaでインストールしたPythonでは実習ができません。」にJupyter、Google Colaboratoryを追記
- [x] 「Jupyter」には公式サイト（ https://jupyter.org/ ）へのリンクを入れる
- [x] 「Google Colaboratory」には公式サイト（ https://colab.research.google.com/?hl=ja ）へのリンクを入れる

**Comment by ikura1** [comment]
やります
