### ISSUE TITLE
7.3. シンプルなWeb APIのコード コラム JSON形式の追加

### ISSUE THREAD

**Issue by zxb04116** [pyconjp/pycamp.pycon.jp#176]
## 目的
文中で扱われているJSONについてコラムを追加する
- この issue の目的
初学者に対して、JSONの大まかな概要を理解しても売らう
## 内容
7.3 コラム　JSON形式
Web APIにデータを送ったり、受け取ったりするときに使われるデータの形式です。データ自体は人間が見ても内容がわかります。プログラムで扱うためには変換が必要な場合があります。

- [ ] この issue で具体的に実施して欲しい内容を
- [ ] 具体的に箇条書きで書く

**Comment by soogie** [comment]
原案はコラムとしては若干内容が薄いので、こうしてはどうでしょうか。

> Web APIにデータを送ったり、受け取ったりするときによく使われるデータの形式です。JavaScript Object Notationという、JavaScriptのオブジェクト表記法を使っています。この表記法は項目名と値のペアをテキストで記述したもので、階層構造にも対応しています。人間が簡単に読み取れて、コンピュータからも扱いやすいため、Pythonを含めさまざまな言語で活用されています。

**Comment by ryu22e** [comment]
@soogie LGTMです 👍
