### ISSUE TITLE
貢献者の名前を書く

### ISSUE THREAD

**Issue by hikaruya8** [pyconjp/pycamp.pycon.jp#179]
## 目的
今日のpycampのメンバーを https://github.com/pyconjp/pycamp.pycon.jp/blob/master/source/organize/3_contributers.rst に追加。
- この issue の目的
各々のGithubのアカウント名とURLをコメントに追加してください。

## 内容
各々のGithubのアカウント名とURLをコメントに追加してください。

**Comment by ikura1** [comment]
https://github.com/ikura1

**Comment by hikaruya8** [comment]
hikaruya8 https://github.com/hikaruya8

**Comment by KobaTomo** [comment]
kobatomo https://github.com/KobaTomo/

**Comment by kuma127** [comment]
kuma127 https://github.com/kuma127

HN: kumappp

**Comment by hamukazu** [comment]
hamukazu https://github.com/hamukazu

**Comment by zxb04116** [comment]
Takeshi_Izawa https://github.com/zxb04116

**Comment by takanory** [comment]
リンクがあれなので、直してほしい

**Comment by takanory** [comment]
すでに直ってた。mergeすみ
