### ISSUE TITLE
4.4 辞書の順序保持についての記述が古い

### ISSUE THREAD

**Issue by soogie** [pyconjp/pycamp.pycon.jp#195]
## 目的

- Python3.7以降では仕様として辞書の順序は保持されるので修正したほうがよい

## 内容

- 「辞書はリストとは違い、各要素に順番を持ちません。代わりにキー（key）と、対応する値（value）を持ちます。」という記述を「辞書の各要素はキー（key）と、対応する値（value）を持ちます。」に修正する

**Comment by soogie** [comment]
修正の際はあわせてリスト4.14，4.16の出力結果（順番が違っている）も修正したい

**Comment by takanory** [comment]
対応されたので閉じます
