### ISSUE TITLE
タプルとリストの違いの説明に辞書のキーになれることも追加する

### ISSUE THREAD

**Issue by t2y** [pyconjp/pycamp.pycon.jp#219]
## 目的

- わかりやすい違いの1つなので項目として紹介してよいと思う

## 内容

* リストとタプルの違いに辞書のキーになれることがない
* 辞書の前にタプルの説明をしているため、説明の順番を入れ替えるとわかりやすいのではないか

## リファレンス

* https://pycamp.pycon.jp/textbook/4_collections.html#index-7

**Comment by kenchang198** [comment]
こちら着手いたします。

**Comment by kenchang198** [comment]
@ryu22e 

>リストとタプルの違いに辞書のキーになれることがない

たしかに、こちらを説明するためには以下の説明順番を入れ替えた方が良いかもしれません。
先に`辞書（dict）`について触れる

**Before**
4.3. タプル（tuple）
4.4. 辞書（dict）

**After**
4.3. 辞書（dict）
4.4. タプル（tuple）

**Comment by ryu22e** [comment]
タプル・辞書の説明順の入れ替えは以下のPRをマージしました。
https://github.com/pyconjp/pycamp.pycon.jp/pull/259

順番を入れ替えただけで説明の内容はまだやっていないので、IssueのCloseはしないでおきます。

**Comment by kenchang198** [comment]
@t2y 
ご確認ありがとうございます！
説明の更新を後ほどコミットいたします！
