### ISSUE TITLE
「繰り返し」「繰返し」の表記ゆれ修正

### ISSUE THREAD

**Issue by ryu22e** [pyconjp/pycamp.pycon.jp#226]
## 目的

- テキスト全体で「繰り返し」と「繰返し」を使っている箇所があるので、どちらかに統一する（現状では「繰り返し」を使っている箇所の方が多い）

## 内容

- [x] 「繰り返し」「繰返し」のどちらに統一するのか決める
- [x] 上記の方針に基づいてテキストを修正

**Comment by soogie** [comment]
国語審議会の議論の中で「繰り返し」だけど読み間違えの恐れがないときは「繰返し」でもよい、という記載がありました（公布された内閣告示の例示からは漏れている）。ということで、「繰り返し」にそろえるとよいと思います。

ソース
- [国語審議会の議論](https://www.bunka.go.jp/kokugo_nihongo/sisaku/joho/joho/kakuki/04/tosin01/index.html)

- [内閣告示](https://www.bunka.go.jp/kokugo_nihongo/sisaku/joho/joho/kijun/naikaku/okurikana/index.html)
