### ISSUE TITLE
devcontainer で執筆環境を簡単に構築できるように

### ISSUE THREAD

**Issue by terapyon** [pyconjp/pycamp.pycon.jp#234]
## 目的

- devcontainer で執筆、改変作業ができるように

## 内容

- [ ] .devcontainer/devcontainer.json を作る
- [ ] 立ち上げの確認

**Comment by shimizukawa** [comment]
watching

**Comment by terapyon** [comment]
@shimizukawa #237 で完了としていいかな？

**Comment by shimizukawa** [comment]
あ、issueあったんですね。完了で良いと思います
