### ISSUE TITLE
７章のWeb APIを取得するコード(films.py)が、実行時にエラーとなる。

### ISSUE THREAD

**Issue by Tetokong** [pyconjp/pycamp.pycon.jp#243]
## 目的

**・7章の「7.3. シンプルなWeb　APIのコード」のサンプルコードが、実行時にエラーになるのを修正
（取得元の 「Star Wars　API」の仕様変更が原因？）**

## 内容

**1. 現状のサンプルコードをコピペして保存、実行すると以下のエラーが発生する。**

　　　　　　**_発生するエラー：TypeError： can only concatenate str (not "int") to str_**

**2.API側の仕様変更で「episode_id」がint型に変わったことが原因と考えられる。**

**3．サンプルコードの「print()」内のプログラムを以下のように修正する。**

![画面ショット](https://github.com/user-attachments/assets/06ac0286-3a89-4657-a752-d2f2cea9c0b8)

　　　　　　　　**修正前：　「　+ film["episode_id"]」
    修正後:「 + str(film["eposode_id"])」
    *文字列型で出力するようにする。**

**Comment by shimizukawa** [comment]
PRマージしましたので、クローズしますね。ありがとうございました！

**Comment by terapyon** [comment]
@shimizukawa あえて、エラーにして、学習の伏線回収（str + int ができない) のためにエラーにしていたってことはないですよね？
明らかなエラーだったので、どっち（APIが変わった or あえてのエラー）だったのかなって疑問になりました。

**Comment by shimizukawa** [comment]
@terapyon わざと、という意図はありませんでした。山形でやったときに、教材にないf-stringを使っていて、それを変更していました。
https://github.com/pyconjp/pycamp.pycon.jp/pull/238/files#r1660068399
山形のときに、idが文字列なのかーと思った記憶はあるので、API変更の可能性はあります。
