### ISSUE TITLE
.github/PULL_REQUEST_TEMPLATE.mdのcontributorに関する説明の更新

### ISSUE THREAD

**Issue by ryu22e** [pyconjp/pycamp.pycon.jp#247]
## 目的

- この issue の目的
   - .github/PULL_REQUEST_TEMPLATE.mdのcontributorに関する説明が一部古い内容のままなので更新する

## 内容

- [ ] .github/PULL_REQUEST_TEMPLATE.mdの `source/organize/3_contributers.rst` を `source/organize/3_contributers.md` に更新する

**Comment by Kaoki729** [comment]
これやります
