### ISSUE TITLE
READMEの「ビルド環境準備」にdevcontainerを使った環境構築方法について説明を追記する

### ISSUE THREAD

**Issue by ryu22e** [pyconjp/pycamp.pycon.jp#248]
## 目的

- .devcontainer/devcontainer.jsonがあるのに利用方法の説明がないので、活用できるようにREADMEに説明を入れたい

## 内容

- [ ] VSCodeでdevcontainerを使って環境構築をやってみる
- [ ] 環境構築方法をREADMEに書く（必要なら画面スクショも入れる）

**Comment by shimizukawa** [comment]
ありがとうございます～。
私がGItHub Codespacesで使いやすいように追加したもので、ローカルのdevcontainerでの実行までは確認していませんでした。

devcontainerについて手順をていねいに書くと長くなりそうなので、起動方法いくつかあるよ、くらいの説明にして外部サイトにリンクする程度で良いかと思いました。

このあたりでしょうか。
* [GitHub Codespaces のクイックスタート - GitHub Docs](https://docs.github.com/ja/codespaces/getting-started/quickstart)
* [Visual Studio Code を使用して Docker コンテナーを開発環境として使用する - Training | Microsoft Learn](https://learn.microsoft.com/ja-jp/training/modules/use-docker-container-dev-env-vs-code/)

**Comment by SagarChandra07** [comment]
download

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive codepass: changeme

you may need to install the c compiler

**Comment by kenchang198** [comment]
git remote add upstream https://github.com/pyconjp/pycamp.pycon.jp.git
