### ISSUE TITLE
「スクレイピングの対象にするページの例」を載せる

### ISSUE THREAD

**Issue by ryu22e** [pyconjp/pycamp.pycon.jp#25]
Issue #16 から別チケットに分けた。

**Comment by takanory** [comment]
@ryu22e 具体的にどういうこと書けばいいですかね

**Comment by ryu22e** [comment]
@takanory 
Issue #16 のこの文を別Issueにしたつもりだったのですが、今読み返すとタイトルが全然違ってました :cry: 
>テキストに例としていい感じのページの例とか載せとくとよいかも

サンプルコードというか、「スクレイピングの対象にするページの例」を載せるということです。Issueタイトルも変更しておきます。
対象のページのソースコードを載せると分量が多すぎるので、「このページを対象にします」という説明付きでリンクを貼っておけばいいかと思います。

**Comment by takanory** [comment]
@ryu22e こんな感じで書いたんで、closeしてもいいですかね

http://pycamp.pycon.jp/textbook/7_scraping.html#html

**Comment by ryu22e** [comment]
@takanory はい、いいと思います 👍

**Comment by takanory** [comment]
お許しがでたのでcloseする
