### ISSUE TITLE
「`print` 関数」という表記を「`print()` 関数」に変更

### ISSUE THREAD

**Issue by ryu22e** [pyconjp/pycamp.pycon.jp#251]
## 目的

- この issue の目的
    - 関数名の表記方法を統一する（最後にカッコを入れる表記にする）

## 内容

- [ ] 「`print` 関数」という表記を「`print()` 関数」に変更

**Comment by Kaoki729** [comment]
これに対応します

**Comment by ryu22e** [comment]
関連PR: https://github.com/pyconjp/pycamp.pycon.jp/pull/254
