### ISSUE TITLE
スクレイピングのサンプルコードで参照するURLをhttps://docs.python.org/ja/3.10/library/functions.html から https://docs.python.org/ja/3.12/library/functions.html に変更

### ISSUE THREAD

**Issue by ryu22e** [pyconjp/pycamp.pycon.jp#253]
## 目的

- [スクレイピングのサンプルコード](https://pycamp.pycon.jp/textbook/7_scraping.html#id24)の参照URLを最新のPythonドキュメントURLにする

## 内容

- [x] [スクレイピングのサンプルコード](https://pycamp.pycon.jp/textbook/7_scraping.html#id24)で参照するURLをhttps://docs.python.org/ja/3.10/library/functions.html から https://docs.python.org/ja/3.12/library/functions.html に変更（スクレイピングのコードも修正の必要あり）
- [x] 「[リスト 7.12  スクレイピングを実行](https://pycamp.pycon.jp/textbook/7_scraping.html#id25)」を上記で修正したコードの実行結果に変更する（`dl`タグを抽出対象にすると関数名が重複してしまうので、対象を`table`に変更したほうがよさそう）

**Comment by naoyasugita** [comment]
確認します！
