### ISSUE TITLE
「モジュール」に関して説明の補足

### ISSUE THREAD

**Issue by ryu22e** [pyconjp/pycamp.pycon.jp#28]
Issue #21 から分けた。

> モジュールまたは関数しかインポートできないような印象を受けました
> 何がエクスポートされるのかの説明 (cf. C言語だとヘッダファイルが必要)
> パッケージについての説明

**Comment by terapyon** [comment]
どのような補足を入れたいのか、意図がわかりませんでした。
具体的にどのような説明を入れるべきか教えて下さい。

**Comment by ryu22e** [comment]
@terapyon 

以下の例だと関数をインポートする例しか書かれていませんが、クラスや変数などをインポートする例も追加してインポートが関数以外にも使えることが分かる補足を入れるようお願いします。
http://bootcamp-text.readthedocs.io/textbook/5_module.html#guide-module

**Comment by terapyon** [comment]
古い指摘で、さらにこのテキストですでに何度もやっているのでこのIssueはやらないでクローズする。
