### ISSUE TITLE
2.5.2. モジュールのインポートの説明に、相対インポートやインポート優先順などの説明はいらないか？

### ISSUE THREAD

**Issue by terapyon** [pyconjp/pycamp.pycon.jp#55]

**Comment by HDisc** [comment]
やってみます！

**Comment by takanory** [comment]
まずは必要かどうかを議論してほしい
Python Boot Campのチュートリアルのレベルだと、そこまで説明しなくていいかなーと思っています

**Comment by ryu22e** [comment]
PyCon JP 2024スプリントの参加者と、このIsssueに着手すべきかどうか議論しました。
結論としては、テキストには盛り込まずに、チュートリアルで実際につまづいている人を講師やTAが個別にフォローするという方針でいいという意見になりました。
参加者の皆さんに、自分が初心者のころに相対インポート周りではまった経験を聞いてみましたが、あると答えたのは6名中1名のみでした。チュートリアルのたびに出てくる疑問ならテキストに入れる価値はありそうですが、そうでもなさそうなので、そこまで必要ではないという話をしました。
