### ISSUE TITLE
windows環境でファイルを読み書きするときの文字コードに付いて

### ISSUE THREAD

**Issue by hrsano645** [pyconjp/pycamp.pycon.jp#71]
はじめまして。PyConJP 2016でpython bootcampのコミュニティブースで立ち寄らせていただいた佐野と申します。(twitter:hrs_sano645) 先日はありがとうございました。
（挨拶は早々としまして）

Windows環境(windows 8.1,10)にてテキストを利用してBootcampを試していましたが、1.5.1.2, 1.5.1.3のファイルの読み込み,クローズで説明されてるwithステートメントの部分で、todo.txtに日本語を含めると以下のようなエラーが出ます。（次の例はwithステートメントでファイルを開いた場合です）

``` python
>>> with open('todo.txt') as f:
...     print(f.read())
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
UnicodeDecodeError: 'cp932' codec can't decode byte 0xef in position 60: illegal multibyte sequence
```

todo.txtの中身はこちらです。

> Write the book
> Try new python libraries
> 日本語テスト

todo.txtは推奨エディタのatomで作りました。その際に文字コードをutf-8で保存する、Windowsコマンドプロント上で実行することで、エラーを起こすようです。  
初学者がつまづきやすい点でもあるので予め回避したほうが良いかと考えています。

対処法は以下が挙げれそうです。その場でお手軽にやるならopen関数側の引数指定かと思いますが、いかがでしょうか？
- open関数にencoding="utf8"の引数指定
- 環境変数 PYTHONIOENCODINGの指定

**Comment by terapyon** [comment]
Python3 で実行した場合、このようなエラーが出ますか？
(Python2だと、 'cp932' が、 'ascii' になるか？？)

Python3 からファイルをOpenする時に、ファイルのエンコーディングをUTF-8として開くように仕様が変わったと記憶しています。環境変数が変わるインストールパターンが有るのかもしれません。

**Comment by hrsano645** [comment]
> Python3 で実行した場合、このようなエラーが出ますか？
python3.5.2で検証しました（書き損ねてました。すみません。）

Python3のインストール時点で影響が出るとなると問題ない場合もあるのですね。どういったときに起こるかは少し気になります。
Win10, インストーラーはweb baseとexecutable の両方で試しましたが同じ現象でした。

**Comment by shimizukawa** [comment]
http://docs.python.jp/3/library/functions.html#open
> テキストモードでは、encoding が指定されていない場合に使われるエンコーディングはプラットフォームに依存します:locale.getpreferredencoding(False) を使って現在のロケールエンコーディングを取得します。

http://docs.python.jp/3/library/locale.html#locale.getpreferredencoding
> テキストデータをエンコードする方法を、ユーザの設定に基づいて返します。ユーザの設定は異なるシステム間では異なった方法で表現され、システムによってはプログラミング的に得ることができないこともあるので、この関数が返すのはただの推測です。
```
> python
Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.getpreferredencoding(False)
'cp932'
```

日本語Windowsではcp932なので、 `open()` がデフォルトでutf-8でファイルを開くことはありません。
encodingを指定するようテキストを修正するのがよいでしょう。

なお、 `PYTHONIOENCODING` でこの挙動が変更されることもないと思います。
```
> set PYTHONIOENCODING=utf-8
> python
Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.getpreferredencoding(False)
'cp932'
```

**Comment by takanory** [comment]
@hrsano645 @shimizukawa レビューよろ https://github.com/pyconjp/bootcamp-text/pull/72

**Comment by shimizukawa** [comment]
reviewed

**Comment by takanory** [comment]
対応ed

**Comment by hrsano645** [comment]
ありがとうございます！

**Comment by takanory** [comment]
@hrsano645 OKだったらこのissue closeしてくださいませ

**Comment by takanory** [comment]
@shimizukawa なんかリンクが違うww

**Comment by takanory** [comment]
だいぶ前のissueだし閉じよ

**Comment by hrsano645** [comment]
すみません。すっかり忘れていました。クローズありがとうございます。
