### ISSUE TITLE
f.write()後にf.close()を記述する

### ISSUE THREAD

**Issue by qt-luigi** [pyconjp/pycamp.pycon.jp#80]
## 目的

- 5.1のファイル書き込みにて、f.write()の後にf.close()に関する記述を行う。

## 内容

- [ ] 5.1.4と5.1.5でのf.write()した後から書き込んだファイルの内容を確認するまでの間にf.close()のコード記述や説明文を追加して欲しい。

## 背景

皆様はじめまして。私は2017年4月9日に本テキストを使用した [尾道Python3入門勉強会（もくもく会）](https://onomiti-frontend.connpass.com/event/52409/) での講師を予定している者で、現在、予習として本テキストの読み込みや動作確認を行なっております。

「5.1.4.ファイルへの書き込み」と「5.1.5.追記モードでの書き込み」ですが、f.write()した後から書き込んだファイルの内容を確認するまでの間に、f.close()のコード記述やf.close()を呼び出す旨の記述があった方がよいと思われますが、如何でしょうか？

テキストをそのまま読み進めると、f.close()しないでCtrl+D(or Z)して対話モードを抜けてファイルの内容を確認してしまい、ファイルを開くためのシステム資源が解放されない恐れがあります。Windowsではファイルオブジェクトの扱いが他OSよりシビアだと聞いたことがあります。

勉強会では講師が補足説明すれば良いのですが、本テキストだけで自己学習を進めている方には気付かれにくく、また「ファイルをopen()したらclose()する」というコーディング作法を学習したり認識したりして頂けると思います。

コードの追加で対応するか、文章を変更するか、どこに記述するか、など、テキストの具体的な変更について自分では判断しきれなかったため、こちらへ投稿させて頂きました。

以上、よろしくお願い致します。

**Comment by shimizukawa** [comment]
指摘ありがとうございます。

> テキストをそのまま読み進めると、f.close()しないでCtrl+D(or Z)して対話モードを抜けてファイルの内容を確認してしまい、ファイルを開くためのシステム資源が解放されない恐れがあります。Windowsではファイルオブジェクトの扱いが他OSよりシビアだと聞いたことがあります。

Pythonのプロセスを終了したのに「ファイルを開くためのシステム資源が解放されない」ということは起こらないので安心してください。CPythonであれ他のPython実装系であれ、プロセス終了時にはメモリが開放され、ファイルハンドラも閉じて返却されます。ファイルをcloseしないで問題になるのは、Pythonプロセスを起動しっぱなしで千個、1万個のファイルを開き続けた場合に同時に開けるファイル数の上限に達してしまった場合などですが、ファイルを開いた変数を保持していなければ順次開放されていくため、これもすぐには問題になりません。ただ、順次開放を待つのではなく使い終わったら明示的にcloseする方が良い、という観点で説明するのは良い修正だと思います。

別の観点で修正が要りそうなのは、writeした直後にPythonの対話モードを起動したままだと、バッファリングされていてファイルを別のエディタ等で開いてもまだ書き出されておらず、内容を確認できない場合があることです。これについては確認前にclose()するか、flush()するかの説明がいりそうですね。

上記を踏まえ、修正の方向性は以下のような感じでどうでしょう。

* ファイルは使い終わったらclose()しよう（良いプラクティス）
* ファイルを開いたままだとバッファリングされてるのでclose()するかflush()するかしよう（機能上の制約）

私が把握している範囲でcloseしない場合の問題とテキストの修正方針を書いてみましたが、上記以外の具体的な問題が出ていたらお教えください。

**Comment by qt-luigi** [comment]
ファイルハンドラー解放の解説ありがとうございます。
理解することができました。
修正の方向性ですがshimizukawaさんの内容で大丈夫です。

**Comment by qt-luigi** [comment]
本日の勉強会にて特に問題ありませんでしたのでクローズさせて頂きます。ありがとうございました。
