### ISSUE TITLE
pip3の補足説明が欲しい

### ISSUE THREAD

**Issue by qt-luigi** [pyconjp/pycamp.pycon.jp#81]
## 目的

- 6.1.1にて、pip3の補足説明を追加して頂く。

## 内容

- [ ] macOSにはApple社の2.7が初期インストールされており、公式インストーラーで3系をインストールするとpip3という名前でインストールされます。pipだけの記述ではインストールされていないように捉えられてしまい余計なバージョンのpipをインストールして時間を費やしたり開発環境を壊したりしてしまう可能性があります。

**Comment by qt-luigi** [comment]
macOSにて、venv環境ではpipで大丈夫でした。

```
$ python3 -m venv env
$ source env/bin/activate
(env)$ pip install requests
Collecting requests
  Downloading requests-2.13.0-py2.py3-none-any.whl (584kB)
    100% |████████████████████████████████| 593kB 536kB/s 
Installing collected packages: requests
Successfully installed requests-2.13.0
```

**Comment by takanory** [comment]
@qt-luigi このテキストでは venv 環境作ってから pip 使ってもらう想定なので、pip3 のことは書かなくていいかなーと思ってますが、どうでしょう?

**Comment by qt-luigi** [comment]
回答ありがとうございます。私の方で2系と3系の混在環境を仮定したのが誤りですね。
本テキストは3系を前提とされているのでtakanoryさんの想定で大丈夫です。

**Comment by takanory** [comment]
ではcloseで

**Comment by qt-luigi** [comment]
ありがとうございます。
