### ISSUE TITLE
今後の進め方のページを書く

### ISSUE THREAD

**Issue by takanory** [pyconjp/pycamp.pycon.jp#83]
## 目的

- 今後どういう風に進めていけばいいかのページを追加する

## 内容

- [ ] コミュニティ紹介
- [ ] slack紹介
- [ ] QAサイト紹介
- [ ] あとなんかるかなぁ

## Pull Requets

- https://github.com/pyconjp/pycamp.pycon.jp/pull/85

**Comment by takanory** [comment]
だいたい書いたんでレビューしてもらう

**Comment by terapyon** [comment]
もう少し何かを書き加えたいけど、思いつかいないのでこれで良いと思います。

**Comment by takanory** [comment]
merge した https://github.com/pyconjp/pycamp.pycon.jp/pull/85

**Comment by takanory** [comment]
mergeしたので閉じる
