### ISSUE TITLE
標準ライブラリの紹介で正規表現モジュールを使うのをやめたい

### ISSUE THREAD

**Issue by jbking** [pyconjp/pycamp.pycon.jp#90]
## 目的

- 正規表現モジュールは標準ライブラリのなかでも多機能、そもそも正規表現のシステム自体が複雑であり、これをブートキャンプの文脈で紹介してもよいか疑問視している。
- 対象者によりふさわしい標準ライブラリの紹介に切り換えてはどうか。

## 内容

- [x] 正規表現モジュールが文脈的にふさわしいか評価する
- [x] ふさわしくない場合は別のモジュールの選定およびテキストの書き換え

**Comment by takanory** [comment]
@jbking datetimeが追加されました!!

**Comment by jbking** [comment]
👍
